[package]
name = "cli_flappy_bird"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_size = "0.2.5"
device_query = "1.1.3"
substring = "1.4.5"
rand = "0.8.5"

